test:
  - tests/**/*
documentation:
  - docs/**/*
  - '**/*.md'
dependencies:
  - package-lock.json
  - yarn.lockfile
ci:
  - .github/workflows/*
  - .travis.yml
github:
  - .github/**/*
git:
  - .gitignore
npm:
  - .npmignore
  - package.json
deployment:
  - netlify.toml
  - _redirects
rollup:
  - rollup.config.js
  - rollup.config.mjs
labels:
  - .github/pr_labeler.yml
vscode:
  - .vscode/*
openapi:
  - openapi/*
